# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\x05proto\"\x1e\n\nLLMRequest\x12\x10\n\x08question\x18\x01 \x01(\t\"\x1a\n\x08LLMReply\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t20\n\x03LLM\x12)\n\x03\x41sk\x12\x11.proto.LLMRequest\x1a\x0f.proto.LLMReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LLMREQUEST']._serialized_start=20
  _globals['_LLMREQUEST']._serialized_end=50
  _globals['_LLMREPLY']._serialized_start=52
  _globals['_LLMREPLY']._serialized_end=78
  _globals['_LLM']._serialized_start=80
  _globals['_LLM']._serialized_end=128
# @@protoc_insertion_point(module_scope)
